ruyi:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: ruyi
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    database: 0
#    password: redis
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: xxx
    access-key-secret: yyy
    bucket-name: ruyi-itcast
  wechat:
    appid: xx
    secret: yy