server:
  port: 8080

spring:
  profiles:
    active: dev  #修改成dev
  datasource:
    druid:
      driver-class-name: ${ruyi.datasource.driver-class-name}
      url: jdbc:mysql://${ruyi.datasource.host}:${ruyi.datasource.port}/${ruyi.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${ruyi.datasource.username}
      password: ${ruyi.datasource.password}

  redis:
    host: ${ruyi.redis.host}
    port: ${ruyi.redis.port}
    database: ${ruyi.redis.database}
    password: ${ruyi.redis.password}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ruyi.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      ruyi:
        mapper: debug
        service: info
        controller: info

ruyi:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: rjlxqh
    # 设置jwt过期时间
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    user-token-name: authentication
  alioss:
    endpoint: ${ruyi.alioss.endpoint}
    access-key-id: ${ruyi.alioss.access-key-id}
    access-key-secret: ${ruyi.alioss.access-key-secret}
    bucket-name: ${ruyi.alioss.bucket-name}
  wechat:
    appid: ${ruyi.wechat.appid}
    secret: ${ruyi.wechat.secret}
